baseURL = "https://sellerkeys.com/"
languageCode = "en-us"
title = "SellerKeys"
theme = "reveal-hugo"
publishDir = "docs"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true